# Generated by Django 3.2.4 on 2021-07-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
