# Generated by Django 3.2.4 on 2021-07-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210729_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profileImg',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
