# Generated by Django 3.2.4 on 2021-07-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customer_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
